// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (space_id, code_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING expires_at
`

type CreateInviteParams struct {
	SpaceID   uuid.UUID
	CodeHash  []byte
	CreatedBy uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.SpaceID,
		arg.CodeHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, status, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.password_hash, u.display_name, u.status, u.created_at FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.status = 'active'
`

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, status, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const redeemInvite = `-- name: RedeemInvite :one
UPDATE invites SET used_by = $1, used_at = now()
WHERE code_hash = $2 AND used_at IS NULL AND expires_at > now()
RETURNING space_id
`

type RedeemInviteParams struct {
	UserID   uuid.NullUUID
	CodeHash []byte
}

// Atomic: a concurrent redeem blocks on the row, then sees used_at set and matches nothing.
func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, redeemInvite, arg.UserID, arg.CodeHash)
	var space_id uuid.UUID
	err := row.Scan(&space_id)
	return space_id, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
