// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canvases.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCanvas = `-- name: CreateCanvas :one
INSERT INTO canvases (space_id, name)
VALUES ($1, $2)
RETURNING id, space_id, name, width, height, palette, cooldown_seconds, created_at
`

type CreateCanvasParams struct {
	SpaceID uuid.UUID
	Name    string
}

func (q *Queries) CreateCanvas(ctx context.Context, arg CreateCanvasParams) (Canvas, error) {
	row := q.db.QueryRow(ctx, createCanvas, arg.SpaceID, arg.Name)
	var i Canvas
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.Palette,
		&i.CooldownSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const getCanvas = `-- name: GetCanvas :one
SELECT id, space_id, name, width, height, palette, cooldown_seconds, created_at FROM canvases
WHERE id = $1 AND space_id = $2
`

type GetCanvasParams struct {
	ID      uuid.UUID
	SpaceID uuid.UUID
}

func (q *Queries) GetCanvas(ctx context.Context, arg GetCanvasParams) (Canvas, error) {
	row := q.db.QueryRow(ctx, getCanvas, arg.ID, arg.SpaceID)
	var i Canvas
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.Palette,
		&i.CooldownSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const listCanvasPixels = `-- name: ListCanvasPixels :many
SELECT x, y, color FROM canvas_pixels
WHERE canvas_id = $1 AND space_id = $2
`

type ListCanvasPixelsParams struct {
	CanvasID uuid.UUID
	SpaceID  uuid.UUID
}

type ListCanvasPixelsRow struct {
	X     int16
	Y     int16
	Color int16
}

func (q *Queries) ListCanvasPixels(ctx context.Context, arg ListCanvasPixelsParams) ([]ListCanvasPixelsRow, error) {
	rows, err := q.db.Query(ctx, listCanvasPixels, arg.CanvasID, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCanvasPixelsRow
	for rows.Next() {
		var i ListCanvasPixelsRow
		if err := rows.Scan(&i.X, &i.Y, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCanvases = `-- name: ListCanvases :many
SELECT id, space_id, name, width, height, palette, cooldown_seconds, created_at FROM canvases
WHERE space_id = $1
ORDER BY id DESC
`

func (q *Queries) ListCanvases(ctx context.Context, spaceID uuid.UUID) ([]Canvas, error) {
	rows, err := q.db.Query(ctx, listCanvases, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Canvas
	for rows.Next() {
		var i Canvas
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Width,
			&i.Height,
			&i.Palette,
			&i.CooldownSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenant = `-- name: SetTenant :exec
SELECT set_config('app.tenant_id', $1::text, true)
`

func (q *Queries) SetTenant(ctx context.Context, spaceID string) error {
	_, err := q.db.Exec(ctx, setTenant, spaceID)
	return err
}
