// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Canvas struct {
	ID              uuid.UUID
	SpaceID         uuid.UUID
	Name            string
	Width           int16
	Height          int16
	Palette         string
	CooldownSeconds int32
	CreatedAt       time.Time
}

type CanvasPixel struct {
	CanvasID uuid.UUID
	X        int16
	Y        int16
	SpaceID  uuid.UUID
	Color    int16
	PixelID  int64
}

type Space struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
}
