// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Canvas struct {
	ID              uuid.UUID
	SpaceID         uuid.UUID
	Name            string
	Width           int16
	Height          int16
	Palette         string
	CooldownSeconds int32
	CreatedAt       time.Time
	CreatedBy       uuid.NullUUID
}

type CanvasPixel struct {
	CanvasID uuid.UUID
	X        int16
	Y        int16
	SpaceID  uuid.UUID
	Color    int16
	PixelID  int64
}

type Invite struct {
	ID        uuid.UUID
	SpaceID   uuid.UUID
	CodeHash  []byte
	CreatedBy uuid.UUID
	ExpiresAt time.Time
	UsedBy    uuid.NullUUID
	UsedAt    *time.Time
}

type Pixel struct {
	ID       int64
	SpaceID  uuid.UUID
	CanvasID uuid.UUID
	X        int16
	Y        int16
	Color    int16
	UserID   uuid.NullUUID
	Source   string
	PlacedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type Space struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
}

type SpaceMember struct {
	SpaceID      uuid.UUID
	UserID       uuid.UUID
	Role         string
	LastPlacedAt *time.Time
	JoinedAt     time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  string
	Status       string
	CreatedAt    time.Time
}

type WsTicket struct {
	TicketHash []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	UsedAt     *time.Time
}
