// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pixels.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimCooldown = `-- name: ClaimCooldown :one
UPDATE space_members SET last_placed_at = now()
WHERE space_id = $1 AND user_id = $2
  AND (last_placed_at IS NULL OR last_placed_at <= now() - make_interval(secs => $3::int))
RETURNING last_placed_at::timestamptz AS placed_at
`

type ClaimCooldownParams struct {
	SpaceID         uuid.UUID
	UserID          uuid.UUID
	CooldownSeconds int32
}

// Atomic: of two concurrent claims, the second sees the first's timestamp and matches nothing.
func (q *Queries) ClaimCooldown(ctx context.Context, arg ClaimCooldownParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, claimCooldown, arg.SpaceID, arg.UserID, arg.CooldownSeconds)
	var placed_at time.Time
	err := row.Scan(&placed_at)
	return placed_at, err
}

const getLastPlacedAt = `-- name: GetLastPlacedAt :one
SELECT last_placed_at FROM space_members
WHERE space_id = $1 AND user_id = $2
`

type GetLastPlacedAtParams struct {
	SpaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetLastPlacedAt(ctx context.Context, arg GetLastPlacedAtParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, getLastPlacedAt, arg.SpaceID, arg.UserID)
	var last_placed_at *time.Time
	err := row.Scan(&last_placed_at)
	return last_placed_at, err
}

const insertPixel = `-- name: InsertPixel :one
INSERT INTO pixels (space_id, canvas_id, x, y, color, user_id, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, placed_at
`

type InsertPixelParams struct {
	SpaceID  uuid.UUID
	CanvasID uuid.UUID
	X        int16
	Y        int16
	Color    int16
	UserID   uuid.NullUUID
	Source   string
}

type InsertPixelRow struct {
	ID       int64
	PlacedAt time.Time
}

func (q *Queries) InsertPixel(ctx context.Context, arg InsertPixelParams) (InsertPixelRow, error) {
	row := q.db.QueryRow(ctx, insertPixel,
		arg.SpaceID,
		arg.CanvasID,
		arg.X,
		arg.Y,
		arg.Color,
		arg.UserID,
		arg.Source,
	)
	var i InsertPixelRow
	err := row.Scan(&i.ID, &i.PlacedAt)
	return i, err
}

const upsertCanvasPixel = `-- name: UpsertCanvasPixel :exec
INSERT INTO canvas_pixels (canvas_id, x, y, space_id, color, pixel_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (canvas_id, x, y) DO UPDATE SET color = EXCLUDED.color, pixel_id = EXCLUDED.pixel_id
`

type UpsertCanvasPixelParams struct {
	CanvasID uuid.UUID
	X        int16
	Y        int16
	SpaceID  uuid.UUID
	Color    int16
	PixelID  int64
}

func (q *Queries) UpsertCanvasPixel(ctx context.Context, arg UpsertCanvasPixelParams) error {
	_, err := q.db.Exec(ctx, upsertCanvasPixel,
		arg.CanvasID,
		arg.X,
		arg.Y,
		arg.SpaceID,
		arg.Color,
		arg.PixelID,
	)
	return err
}
