// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO space_members (space_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (space_id, user_id) DO NOTHING
`

type AddMemberParams struct {
	SpaceID uuid.UUID
	UserID  uuid.UUID
	Role    string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.SpaceID, arg.UserID, arg.Role)
	return err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name, slug) VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateSpaceParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.Name, arg.Slug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM space_members
WHERE space_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	SpaceID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.SpaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUserSpaces = `-- name: ListUserSpaces :many
SELECT s.id, s.name, s.slug, m.role
FROM space_members m
JOIN spaces s ON s.id = m.space_id
WHERE m.user_id = $1
ORDER BY m.joined_at
`

type ListUserSpacesRow struct {
	ID   uuid.UUID
	Name string
	Slug string
	Role string
}

func (q *Queries) ListUserSpaces(ctx context.Context, userID uuid.UUID) ([]ListUserSpacesRow, error) {
	rows, err := q.db.Query(ctx, listUserSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSpacesRow
	for rows.Next() {
		var i ListUserSpacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
