// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SpaceMembershipRole.
const (
	Member SpaceMembershipRole = "member"
	Owner  SpaceMembershipRole = "owner"
)

// Valid indicates whether the value is a known member of the SpaceMembershipRole enum.
func (e SpaceMembershipRole) Valid() bool {
	switch e {
	case Member:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for WSClientMessageType.
const (
	Subscribe   WSClientMessageType = "subscribe"
	Unsubscribe WSClientMessageType = "unsubscribe"
)

// Valid indicates whether the value is a known member of the WSClientMessageType enum.
func (e WSClientMessageType) Valid() bool {
	switch e {
	case Subscribe:
		return true
	case Unsubscribe:
		return true
	default:
		return false
	}
}

// Defines values for WSServerMessageType.
const (
	WSServerMessageTypeError       WSServerMessageType = "error"
	WSServerMessageTypePixelPlaced WSServerMessageType = "pixel:placed"
	WSServerMessageTypeSubscribed  WSServerMessageType = "subscribed"
)

// Valid indicates whether the value is a known member of the WSServerMessageType enum.
func (e WSServerMessageType) Valid() bool {
	switch e {
	case WSServerMessageTypeError:
		return true
	case WSServerMessageTypePixelPlaced:
		return true
	case WSServerMessageTypeSubscribed:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token Send as Authorization: Bearer <token>
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Canvas defines model for Canvas.
type Canvas struct {
	CooldownSeconds int                `json:"cooldownSeconds"`
	CreatedAt       time.Time          `json:"createdAt"`
	Height          int                `json:"height"`
	Id              openapi_types.UUID `json:"id"`
	Name            string             `json:"name"`
	Palette         Palette            `json:"palette"`
	Width           int                `json:"width"`
}

// CanvasList defines model for CanvasList.
type CanvasList struct {
	Canvases []Canvas `json:"canvases"`
}

// CooldownError defines model for CooldownError.
type CooldownError struct {
	Error       string    `json:"error"`
	NextPlaceAt time.Time `json:"nextPlaceAt"`
}

// CreateCanvasRequest defines model for CreateCanvasRequest.
type CreateCanvasRequest struct {
	// CooldownSeconds Default 10
	CooldownSeconds *int   `json:"cooldownSeconds,omitempty"`
	Name            string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Env    string `json:"env"`
	Status string `json:"status"`
}

// Invite defines model for Invite.
type Invite struct {
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// JoinRequest defines model for JoinRequest.
type JoinRequest struct {
	Code string `json:"code"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Spaces []SpaceMembership `json:"spaces"`
	User   User              `json:"user"`
}

// Palette defines model for Palette.
type Palette struct {
	// Colors Hex colors. A cell's byte is an index into this list.
	Colors []string `json:"colors"`
	Id     string   `json:"id"`
}

// PlacePixelRequest defines model for PlacePixelRequest.
type PlacePixelRequest struct {
	// Color Index into the canvas palette
	Color int `json:"color"`
	X     int `json:"x"`
	Y     int `json:"y"`
}

// PlacedPixel defines model for PlacedPixel.
type PlacedPixel struct {
	Color       int       `json:"color"`
	NextPlaceAt time.Time `json:"nextPlaceAt"`
	PixelId     int64     `json:"pixelId"`
	PlacedAt    time.Time `json:"placedAt"`
	X           int       `json:"x"`
	Y           int       `json:"y"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Code        string `json:"code"`
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

// SpaceMembership defines model for SpaceMembership.
type SpaceMembership struct {
	Id   openapi_types.UUID  `json:"id"`
	Name string              `json:"name"`
	Role SpaceMembershipRole `json:"role"`
	Slug string              `json:"slug"`
}

// SpaceMembershipRole defines model for SpaceMembership.Role.
type SpaceMembershipRole string

// User defines model for User.
type User struct {
	DisplayName string             `json:"displayName"`
	Email       string             `json:"email"`
	Id          openapi_types.UUID `json:"id"`
}

// WSClientMessage defines model for WSClientMessage.
type WSClientMessage struct {
	CanvasId openapi_types.UUID  `json:"canvasId"`
	SpaceId  openapi_types.UUID  `json:"spaceId"`
	Type     WSClientMessageType `json:"type"`
}

// WSClientMessageType defines model for WSClientMessage.Type.
type WSClientMessageType string

// WSServerMessage defines model for WSServerMessage.
type WSServerMessage struct {
	CanvasId *openapi_types.UUID `json:"canvasId,omitempty"`
	Color    *int                `json:"color,omitempty"`
	Error    *string             `json:"error,omitempty"`
	PixelId  *int64              `json:"pixelId,omitempty"`
	Type     WSServerMessageType `json:"type"`
	X        *int                `json:"x,omitempty"`
	Y        *int                `json:"y,omitempty"`
}

// WSServerMessageType defines model for WSServerMessage.Type.
type WSServerMessageType string

// WSTicket defines model for WSTicket.
type WSTicket struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Ticket    string    `json:"ticket"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// JoinSpaceJSONRequestBody defines body for JoinSpace for application/json ContentType.
type JoinSpaceJSONRequestBody = JoinRequest

// CreateCanvasJSONRequestBody defines body for CreateCanvas for application/json ContentType.
type CreateCanvasJSONRequestBody = CreateCanvasRequest

// PlacePixelJSONRequestBody defines body for PlacePixel for application/json ContentType.
type PlacePixelJSONRequestBody = PlacePixelRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/signup)
	Signup(w http.ResponseWriter, r *http.Request)

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (POST /spaces/join)
	JoinSpace(w http.ResponseWriter, r *http.Request)

	// (GET /spaces/{spaceId}/canvases)
	ListCanvases(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID)

	// (POST /spaces/{spaceId}/canvases)
	CreateCanvas(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID)

	// (GET /spaces/{spaceId}/canvases/{canvasId}/board)
	GetCanvasBoard(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID)

	// (POST /spaces/{spaceId}/canvases/{canvasId}/pixels)
	PlacePixel(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID)

	// (POST /spaces/{spaceId}/invites)
	CreateInvite(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID)

	// (POST /ws/ticket)
	CreateWSTicket(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /auth/signup)
func (_ Unimplemented) Signup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /spaces/join)
func (_ Unimplemented) JoinSpace(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /spaces/{spaceId}/canvases)
func (_ Unimplemented) ListCanvases(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /spaces/{spaceId}/canvases)
func (_ Unimplemented) CreateCanvas(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /spaces/{spaceId}/canvases/{canvasId}/board)
func (_ Unimplemented) GetCanvasBoard(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /spaces/{spaceId}/canvases/{canvasId}/pixels)
func (_ Unimplemented) PlacePixel(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /spaces/{spaceId}/invites)
func (_ Unimplemented) CreateInvite(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /ws/ticket)
func (_ Unimplemented) CreateWSTicket(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinSpace operation middleware
func (siw *ServerInterfaceWrapper) JoinSpace(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinSpace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCanvases operation middleware
func (siw *ServerInterfaceWrapper) ListCanvases(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "spaceId" -------------
	var spaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", chi.URLParam(r, "spaceId"), &spaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "spaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCanvases(w, r, spaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCanvas operation middleware
func (siw *ServerInterfaceWrapper) CreateCanvas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "spaceId" -------------
	var spaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", chi.URLParam(r, "spaceId"), &spaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "spaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCanvas(w, r, spaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCanvasBoard operation middleware
func (siw *ServerInterfaceWrapper) GetCanvasBoard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "spaceId" -------------
	var spaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", chi.URLParam(r, "spaceId"), &spaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "spaceId", Err: err})
		return
	}

	// ------------- Path parameter "canvasId" -------------
	var canvasId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "canvasId", chi.URLParam(r, "canvasId"), &canvasId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "canvasId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCanvasBoard(w, r, spaceId, canvasId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlacePixel operation middleware
func (siw *ServerInterfaceWrapper) PlacePixel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "spaceId" -------------
	var spaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", chi.URLParam(r, "spaceId"), &spaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "spaceId", Err: err})
		return
	}

	// ------------- Path parameter "canvasId" -------------
	var canvasId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "canvasId", chi.URLParam(r, "canvasId"), &canvasId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "canvasId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlacePixel(w, r, spaceId, canvasId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateInvite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "spaceId" -------------
	var spaceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", chi.URLParam(r, "spaceId"), &spaceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "spaceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvite(w, r, spaceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWSTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateWSTicket(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWSTicket(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/signup", wrapper.Signup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/spaces/join", wrapper.JoinSpace)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/spaces/{spaceId}/invites", wrapper.CreateInvite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{spaceId}/canvases", wrapper.ListCanvases)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/spaces/{spaceId}/canvases", wrapper.CreateCanvas)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/spaces/{spaceId}/canvases/{canvasId}/pixels", wrapper.PlacePixel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ws/ticket", wrapper.CreateWSTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/spaces/{spaceId}/canvases/{canvasId}/board", wrapper.GetCanvasBoard)
	})

	return r
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse Error

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429JSONResponse Error

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401JSONResponse Error

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201JSONResponse AuthResponse

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Signup400JSONResponse Error

func (response Signup400JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Signup409JSONResponse Error

func (response Signup409JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Signup429JSONResponse Error

func (response Signup429JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse Error

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type JoinSpaceRequestObject struct {
	Body *JoinSpaceJSONRequestBody
}

type JoinSpaceResponseObject interface {
	VisitJoinSpaceResponse(w http.ResponseWriter) error
}

type JoinSpace200JSONResponse SpaceMembership

func (response JoinSpace200JSONResponse) VisitJoinSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type JoinSpace400JSONResponse Error

func (response JoinSpace400JSONResponse) VisitJoinSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type JoinSpace401JSONResponse Error

func (response JoinSpace401JSONResponse) VisitJoinSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type JoinSpace429JSONResponse Error

func (response JoinSpace429JSONResponse) VisitJoinSpaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListCanvasesRequestObject struct {
	SpaceId openapi_types.UUID `json:"spaceId"`
}

type ListCanvasesResponseObject interface {
	VisitListCanvasesResponse(w http.ResponseWriter) error
}

type ListCanvases200JSONResponse CanvasList

func (response ListCanvases200JSONResponse) VisitListCanvasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCanvases401JSONResponse Error

func (response ListCanvases401JSONResponse) VisitListCanvasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListCanvases404JSONResponse Error

func (response ListCanvases404JSONResponse) VisitListCanvasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCanvasRequestObject struct {
	SpaceId openapi_types.UUID `json:"spaceId"`
	Body    *CreateCanvasJSONRequestBody
}

type CreateCanvasResponseObject interface {
	VisitCreateCanvasResponse(w http.ResponseWriter) error
}

type CreateCanvas201JSONResponse Canvas

func (response CreateCanvas201JSONResponse) VisitCreateCanvasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCanvas400JSONResponse Error

func (response CreateCanvas400JSONResponse) VisitCreateCanvasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCanvas401JSONResponse Error

func (response CreateCanvas401JSONResponse) VisitCreateCanvasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCanvas404JSONResponse Error

func (response CreateCanvas404JSONResponse) VisitCreateCanvasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetCanvasBoardRequestObject struct {
	SpaceId  openapi_types.UUID `json:"spaceId"`
	CanvasId openapi_types.UUID `json:"canvasId"`
}

type GetCanvasBoardResponseObject interface {
	VisitGetCanvasBoardResponse(w http.ResponseWriter) error
}

type GetCanvasBoard200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetCanvasBoard200ApplicationoctetStreamResponse) VisitGetCanvasBoardResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetCanvasBoard401JSONResponse Error

func (response GetCanvasBoard401JSONResponse) VisitGetCanvasBoardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCanvasBoard404JSONResponse Error

func (response GetCanvasBoard404JSONResponse) VisitGetCanvasBoardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePixelRequestObject struct {
	SpaceId  openapi_types.UUID `json:"spaceId"`
	CanvasId openapi_types.UUID `json:"canvasId"`
	Body     *PlacePixelJSONRequestBody
}

type PlacePixelResponseObject interface {
	VisitPlacePixelResponse(w http.ResponseWriter) error
}

type PlacePixel201JSONResponse PlacedPixel

func (response PlacePixel201JSONResponse) VisitPlacePixelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePixel400JSONResponse Error

func (response PlacePixel400JSONResponse) VisitPlacePixelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePixel401JSONResponse Error

func (response PlacePixel401JSONResponse) VisitPlacePixelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePixel404JSONResponse Error

func (response PlacePixel404JSONResponse) VisitPlacePixelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePixel429JSONResponse CooldownError

func (response PlacePixel429JSONResponse) VisitPlacePixelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInviteRequestObject struct {
	SpaceId openapi_types.UUID `json:"spaceId"`
}

type CreateInviteResponseObject interface {
	VisitCreateInviteResponse(w http.ResponseWriter) error
}

type CreateInvite201JSONResponse Invite

func (response CreateInvite201JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvite401JSONResponse Error

func (response CreateInvite401JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvite403JSONResponse Error

func (response CreateInvite403JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateInvite404JSONResponse Error

func (response CreateInvite404JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWSTicketRequestObject struct {
}

type CreateWSTicketResponseObject interface {
	VisitCreateWSTicketResponse(w http.ResponseWriter) error
}

type CreateWSTicket201JSONResponse WSTicket

func (response CreateWSTicket201JSONResponse) VisitCreateWSTicketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateWSTicket401JSONResponse Error

func (response CreateWSTicket401JSONResponse) VisitCreateWSTicketResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (POST /auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)

	// (POST /spaces/join)
	JoinSpace(ctx context.Context, request JoinSpaceRequestObject) (JoinSpaceResponseObject, error)

	// (GET /spaces/{spaceId}/canvases)
	ListCanvases(ctx context.Context, request ListCanvasesRequestObject) (ListCanvasesResponseObject, error)

	// (POST /spaces/{spaceId}/canvases)
	CreateCanvas(ctx context.Context, request CreateCanvasRequestObject) (CreateCanvasResponseObject, error)

	// (GET /spaces/{spaceId}/canvases/{canvasId}/board)
	GetCanvasBoard(ctx context.Context, request GetCanvasBoardRequestObject) (GetCanvasBoardResponseObject, error)

	// (POST /spaces/{spaceId}/canvases/{canvasId}/pixels)
	PlacePixel(ctx context.Context, request PlacePixelRequestObject) (PlacePixelResponseObject, error)

	// (POST /spaces/{spaceId}/invites)
	CreateInvite(ctx context.Context, request CreateInviteRequestObject) (CreateInviteResponseObject, error)

	// (POST /ws/ticket)
	CreateWSTicket(ctx context.Context, request CreateWSTicketRequestObject) (CreateWSTicketResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(w http.ResponseWriter, r *http.Request) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// JoinSpace operation middleware
func (sh *strictHandler) JoinSpace(w http.ResponseWriter, r *http.Request) {
	var request JoinSpaceRequestObject

	var body JoinSpaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.JoinSpace(ctx, request.(JoinSpaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "JoinSpace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(JoinSpaceResponseObject); ok {
		if err := validResponse.VisitJoinSpaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCanvases operation middleware
func (sh *strictHandler) ListCanvases(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	var request ListCanvasesRequestObject

	request.SpaceId = spaceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCanvases(ctx, request.(ListCanvasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCanvases")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCanvasesResponseObject); ok {
		if err := validResponse.VisitListCanvasesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCanvas operation middleware
func (sh *strictHandler) CreateCanvas(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	var request CreateCanvasRequestObject

	request.SpaceId = spaceId

	var body CreateCanvasJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCanvas(ctx, request.(CreateCanvasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCanvas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCanvasResponseObject); ok {
		if err := validResponse.VisitCreateCanvasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCanvasBoard operation middleware
func (sh *strictHandler) GetCanvasBoard(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID) {
	var request GetCanvasBoardRequestObject

	request.SpaceId = spaceId
	request.CanvasId = canvasId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCanvasBoard(ctx, request.(GetCanvasBoardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCanvasBoard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCanvasBoardResponseObject); ok {
		if err := validResponse.VisitGetCanvasBoardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlacePixel operation middleware
func (sh *strictHandler) PlacePixel(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID, canvasId openapi_types.UUID) {
	var request PlacePixelRequestObject

	request.SpaceId = spaceId
	request.CanvasId = canvasId

	var body PlacePixelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlacePixel(ctx, request.(PlacePixelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlacePixel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlacePixelResponseObject); ok {
		if err := validResponse.VisitPlacePixelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInvite operation middleware
func (sh *strictHandler) CreateInvite(w http.ResponseWriter, r *http.Request, spaceId openapi_types.UUID) {
	var request CreateInviteRequestObject

	request.SpaceId = spaceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvite(ctx, request.(CreateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInviteResponseObject); ok {
		if err := validResponse.VisitCreateInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWSTicket operation middleware
func (sh *strictHandler) CreateWSTicket(w http.ResponseWriter, r *http.Request) {
	var request CreateWSTicketRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWSTicket(ctx, request.(CreateWSTicketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWSTicket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateWSTicketResponseObject); ok {
		if err := validResponse.VisitCreateWSTicketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
